### PR TITLE
make_bags.sh

### PR DESCRIPTION
**Pull request by genfhk**

### CODE REVIEW

**Comment by nkrabben** [comment]
I need to look through this PR. Some of the variables and comments reference the validation script this is based on that I think we should update.

Also, there's an example python script called validate_bags.py that could be adapted too. validate_bags.py has an advantage of validate_bags.sh in that you can choose whether or not to recalculate hashes or just check 0xum and completeness. Also, progress bar! There might be similar features you would want for making bags. Maybe an argument to define where to put the log file.

**Comment by nkrabben** [comment]
nm first part of previous comment, read the wrong commit

I added some additional code to make sure the script only bags if you specify a directory. @genevieve-nypl can you test out the changes?

**Comment by genfhk** [comment]
Sure thing! my Internet is busted right now so it'l have to wait til tomorrow.

**Comment by ablwr** [comment]
y'all don't forget you work 35 hours a week

**Comment by genfhk** [comment]
error: MY-PAMI-061930:test genevievehavemeyerking$ /Users/genevievehavemeyerking/Desktop/make_bags_copy.sh -d /Users/genevievehavemeyerking/Desktop/test 
/Users/genevievehavemeyerking/Desktop/make_bags_copy.sh: line 20: [[: /Users/genevievehavemeyerking/Desktop/test: syntax error: operand expected (error token is "/Users/genevievehavemeyerking/Desktop/test")

**Comment by nkrabben** [comment]
Phew, I'll take a look at this before we meet at 3.

**Comment by nkrabben** [comment]
New issue is that installing this set of tools with "pip install ." might break bagit-python since i have to use a local fork of it. I'll look into fixing setup.py to fix this. Learning opportunities!

**Comment by nkrabben** [comment]
Alright, fixed the bagit-python bug with this commit
https://github.com/NYPL/ami-tools/commit/663f88489c1dd22cc54e196b2fd38fe1984050a5

**Pull request closed without merging**
