### PR TITLE
add general json hash fixer

### PR DESCRIPTION
**Pull request by genfhk**

### CODE REVIEW

**Comment by nkrabben** [comment]
this is a super good fix, but i think there's some help text to fix on another tool. Can you tack that onto this branch?

**Comment by bturkus** [comment]
what does this do exactly? I can't tell from the code

**Comment by nkrabben** [comment]
It fixes a bug I introduced when I added nargs to -b
It also adds a new flag to the json fixer. Previously this tool programmatically fixed two common areas and then updated the bag manifests, etc. Now, if you altered json without this tool, you can run with --badjson and it will update the bag manifests, etc.

**Comment by genfhk** [comment]
> this is a super good fix, but i think there's some help text to fix on another tool. Can you tack that onto this branch?

done with [846fc8d](https://github.com/NYPL/ami-tools/pull/72/commits/846fc8d9fe43a723045890a691f092f6bfb0e9af) - can you review?

**Comment by bturkus** [comment]
@nkrabben is this what we were discussing earlier today?

**Pull request merged**
